/*

 HEARTS.C

 Tile Source File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 16
  Tiles                : 0 to 0

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

/* Start of tile array. */
const unsigned char Hearts[] =
{
  0x66,0x66,0x9F,0xF9,0xBF,0xC1,0xBF,0xC1,
  0xBF,0xC1,0x5E,0x62,0x2C,0x34,0x18,0x18,
  0x66,0x66,0x99,0x99,0x81,0x81,0x81,0x81,
  0x81,0x81,0x42,0x42,0x24,0x24,0x18,0x18
};

/* End of HEARTS.C */
