/*

 DIALOG.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 20
   Tile set      : C:\Users\Equipo\Documents\Shared_Documents\Game\Assets\Dialog.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __Dialog_h_INCLUDE
#define __Dialog_h_INCLUDE

#define DialogWidth 20
#define DialogHeight 20
#define DialogBank 0

extern const unsigned char Dialog[];

#endif

/* End of DIALOG.H */
