//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_Font_H
#define METASPRITE_Font_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define Font_TILE_ORIGIN 0
#define Font_TILE_W 8
#define Font_TILE_H 8
#define Font_WIDTH 416
#define Font_HEIGHT 8
#define Font_TILE_COUNT 52

BANKREF_EXTERN(Font)

extern const uint8_t Font_tiles[832];


#endif
