//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_Heart_H
#define METASPRITE_Heart_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define Heart_TILE_ORIGIN 0
#define Heart_TILE_W 8
#define Heart_TILE_H 8
#define Heart_WIDTH 16
#define Heart_HEIGHT 8
#define Heart_TILE_COUNT 2
#define Heart_PALETTE_COUNT 1
#define Heart_COLORS_PER_PALETTE 4
#define Heart_TOTAL_COLORS 4

BANKREF_EXTERN(Heart)

extern const palette_color_t Heart_palettes[4];
extern const uint8_t Heart_tiles[32];


#endif
