/*

 INVENTORY.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 10
   Tile set      : C:\Users\Equipo\Documents\Shared_Documents\Game\Assets\Dialog.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __Inventory_h_INCLUDE
#define __Inventory_h_INCLUDE

#define InventoryWidth 20
#define InventoryHeight 10
#define InventoryBank 0

extern const unsigned char Inventory[];

#endif

/* End of INVENTORY.H */
