//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_SplashScreen_H
#define METASPRITE_SplashScreen_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define SplashScreen_TILE_ORIGIN 0
#define SplashScreen_TILE_W 8
#define SplashScreen_TILE_H 8
#define SplashScreen_WIDTH 160
#define SplashScreen_HEIGHT 144
#define SplashScreen_TILE_COUNT 59
#define SplashScreen_PALETTE_COUNT 1
#define SplashScreen_COLORS_PER_PALETTE 4
#define SplashScreen_TOTAL_COLORS 4
#define SplashScreen_MAP_ATTRIBUTES 0

BANKREF_EXTERN(SplashScreen)

extern const palette_color_t SplashScreen_palettes[4];
extern const uint8_t SplashScreen_tiles[944];

extern const unsigned char SplashScreen_map[360];

#endif
