//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_DialogTiles_H
#define METASPRITE_DialogTiles_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define DialogTiles_TILE_ORIGIN 0
#define DialogTiles_TILE_W 8
#define DialogTiles_TILE_H 8
#define DialogTiles_WIDTH 72
#define DialogTiles_HEIGHT 8
#define DialogTiles_TILE_COUNT 9
#define DialogTiles_PALETTE_COUNT 1
#define DialogTiles_COLORS_PER_PALETTE 4
#define DialogTiles_TOTAL_COLORS 4

BANKREF_EXTERN(DialogTiles)

extern const palette_color_t DialogTiles_palettes[4];
extern const uint8_t DialogTiles_tiles[144];


#endif
