//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_MapTiles_H
#define METASPRITE_MapTiles_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define MapTiles_TILE_ORIGIN 0
#define MapTiles_TILE_W 8
#define MapTiles_TILE_H 8
#define MapTiles_WIDTH 224
#define MapTiles_HEIGHT 8
#define MapTiles_TILE_COUNT 26

BANKREF_EXTERN(MapTiles)

extern const uint8_t MapTiles_tiles[416];


#endif
