/*

 TILES.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 33

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : 1 Byte per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __Tiles_h_INCLUDE
#define __Tiles_h_INCLUDE

/* Bank of tiles. */
#define TestRoomTilesBank 0

/* Super Gameboy palette 0 */
#define TestRoomTilesSGBPal0c0 6076
#define TestRoomTilesSGBPal0c1 8935
#define TestRoomTilesSGBPal0c2 6596
#define TestRoomTilesSGBPal0c3 5344

/* Super Gameboy palette 1 */
#define TestRoomTilesSGBPal1c0 6076
#define TestRoomTilesSGBPal1c1 8935
#define TestRoomTilesSGBPal1c2 6596
#define TestRoomTilesSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define TestRoomTilesSGBPal2c0 6076
#define TestRoomTilesSGBPal2c1 8935
#define TestRoomTilesSGBPal2c2 6596
#define TestRoomTilesSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define TestRoomTilesSGBPal3c0 6076
#define TestRoomTilesSGBPal3c1 8935
#define TestRoomTilesSGBPal3c2 6596
#define TestRoomTilesSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define TestRoomTilesCGBPal0c0 26623
#define TestRoomTilesCGBPal0c1 21374
#define TestRoomTilesCGBPal0c2 1365
#define TestRoomTilesCGBPal0c3 2188

/* Gameboy Color palette 1 */
#define TestRoomTilesCGBPal1c0 26623
#define TestRoomTilesCGBPal1c1 14143
#define TestRoomTilesCGBPal1c2 243
#define TestRoomTilesCGBPal1c3 0

/* Gameboy Color palette 2 */
#define TestRoomTilesCGBPal2c0 6076
#define TestRoomTilesCGBPal2c1 8935
#define TestRoomTilesCGBPal2c2 6596
#define TestRoomTilesCGBPal2c3 5344

/* Gameboy Color palette 3 */
#define TestRoomTilesCGBPal3c0 6076
#define TestRoomTilesCGBPal3c1 8935
#define TestRoomTilesCGBPal3c2 6596
#define TestRoomTilesCGBPal3c3 5344

/* Gameboy Color palette 4 */
#define TestRoomTilesCGBPal4c0 6076
#define TestRoomTilesCGBPal4c1 8935
#define TestRoomTilesCGBPal4c2 6596
#define TestRoomTilesCGBPal4c3 5344

/* Gameboy Color palette 5 */
#define TestRoomTilesCGBPal5c0 6076
#define TestRoomTilesCGBPal5c1 8935
#define TestRoomTilesCGBPal5c2 6596
#define TestRoomTilesCGBPal5c3 5344

/* Gameboy Color palette 6 */
#define TestRoomTilesCGBPal6c0 6076
#define TestRoomTilesCGBPal6c1 8935
#define TestRoomTilesCGBPal6c2 6596
#define TestRoomTilesCGBPal6c3 5344

/* Gameboy Color palette 7 */
#define TestRoomTilesCGBPal7c0 6076
#define TestRoomTilesCGBPal7c1 8935
#define TestRoomTilesCGBPal7c2 6596
#define TestRoomTilesCGBPal7c3 5344
/* CGBpalette entries. */
extern const unsigned char TestRoomTilesCGB[];
/* Start of tile array. */
extern const unsigned char TestRoomTiles[];

#endif

/* End of TILES.H */
