//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_Glitters_H
#define METASPRITE_Glitters_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define Glitters_TILE_ORIGIN 0
#define Glitters_TILE_W 8
#define Glitters_TILE_H 8
#define Glitters_WIDTH 16
#define Glitters_HEIGHT 8
#define Glitters_TILE_COUNT 2
#define Glitters_PALETTE_COUNT 1
#define Glitters_COLORS_PER_PALETTE 4
#define Glitters_TOTAL_COLORS 4

BANKREF_EXTERN(Glitters)

extern const palette_color_t Glitters_palettes[4];
extern const uint8_t Glitters_tiles[32];


#endif
