//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_lizzie_spr_H
#define METASPRITE_lizzie_spr_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define lizzie_spr_TILE_ORIGIN 0
#define lizzie_spr_TILE_W 8
#define lizzie_spr_TILE_H 16
#define lizzie_spr_WIDTH 16
#define lizzie_spr_HEIGHT 16
#define lizzie_spr_TILE_COUNT 48
#define lizzie_spr_PALETTE_COUNT 2
#define lizzie_spr_COLORS_PER_PALETTE 4
#define lizzie_spr_TOTAL_COLORS 8

BANKREF_EXTERN(lizzie_spr)

extern const palette_color_t lizzie_spr_palettes[8];
extern const uint8_t lizzie_spr_tiles[768];


#endif
