//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_Dialog_H
#define METASPRITE_Dialog_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define Dialog_TILE_ORIGIN 0
#define Dialog_TILE_W 8
#define Dialog_TILE_H 8
#define Dialog_WIDTH 160
#define Dialog_HEIGHT 48
#define Dialog_TILE_COUNT 0
#define Dialog_PALETTE_COUNT 1
#define Dialog_COLORS_PER_PALETTE 4
#define Dialog_TOTAL_COLORS 4
#define Dialog_MAP_ATTRIBUTES Dialog_map_attributes
#define Dialog_MAP_ATTRIBUTES_WIDTH 20
#define Dialog_MAP_ATTRIBUTES_HEIGHT 6
#define Dialog_MAP_ATTRIBUTES_PACKED_WIDTH 20
#define Dialog_MAP_ATTRIBUTES_PACKED_HEIGHT 6

BANKREF_EXTERN(Dialog)


extern const unsigned char Dialog_map[120];
extern const unsigned char Dialog_map_attributes[120];

#endif
